config/routes.rb
Estudo1RorOp1::Application.routes.draw do

  resources :carros

  root to: "carros#index"
  resources "carros"
end

app/models/carro.rb
class Carro < ActiveRecord::Base
	#validates_inclusion_of :prioridade, :in => 1..10

	#attr_accessor :prioridade

	def novo?
		true
	end

	def calcula_comissao
		preco * 0.05
	end
end

app/models/carro_observer.rb
class CarroObserver < ActiveRecord::Observer
	def after_create(carro)
		Notificador.novo_carro(carro, "contato@thiagobaptista.com").deliver
	end
end

app/models/moto.rb
class Moto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
	def index
		@carro = Carro.new
		@carros = Carro.all
	end

	def create
		carro = Carro.new params[:carro]

		carro.save

		redirect_to :action => "index"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/carros/_form.html.erb
<%= form_for(@carro) do |f| %>
  <% if @carro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
      <% @carro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carros/edit.html.erb
<h1>Editing carro</h1>

<%= render 'form' %>

<%= link_to 'Show', @carro %> |
<%= link_to 'Back', carros_path %>

app/views/carros/index.html.erb
<div id="form">
	<%= form_for @carro, :url => {:action => 'create'} do |f| %>
	<strong>Quer vender?</strong>
	<br /><br />

	<%= f.label :nome %><br />
	<%= f.text_field :nome, :class => 'button-input' %>
	<br />

	<%= f.label :descricao %><br />
	<%= f.text_area :descricao, :cols => 26, :rows => 9 %>
	<br />

	<%= f.label :preco %><br />
	<%= f.text_field :preco, :class => 'button-input' %>
	<br />

	<br />

	<%= f.submit "Anunciar!", :disable_with => '...', :class => 'anunciar' %>
	<% end %>
</div><!-- form -->

<div style="clear:both"></div>

<div id="busca">
	<strong>Carros a venda</strong>
	<br />

	<% if !@carros.blank? %>
	<% for carro in @carros %>
	<strong><%= carro.nome %></strong>
	<br />

	<%= carro.descricao %>
	<br />

	R$<%= carro.preco %>
	<br />
	<% end %>
	<% else %>
	<p>Nenhum carro cadastrado.</p>
	<% end %>
</div><!-- busca -->

app/views/carros/new.html.erb
<h1>New carro</h1>

<%= render 'form' %>

<%= link_to 'Back', carros_path %>

app/views/carros/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_carro_path(@carro) %> |
<%= link_to 'Back', carros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/notificador/novo_carro.html.erb
Novo carro cadastrado!
<%= @carro.nome %>
<%= @carro.descricao %>
<%= @carro.preco %>